spring:
  application:
    name: finpulse


  spring.profiles.active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  sql:
    init:
      mode: never
  cache:
    type: redis


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

server:
  port: 8080

management:
  metrics:
    tags:
      application: finpulse
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true

fraud:
  high-count-threshold: 10
  high-receiver-threshold: 5
  repeat-transfer-threshold: 5
  high-amount-threshold: 150000
  high-amount-count-threshold: 5

