# App
spring.application.name=finpulse
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/finpulse_db
spring.datasource.username=root
spring.datasource.password=Pavan@001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


spring.sql.init.mode=never



# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

fraud.high-count-threshold=10
fraud.high-receiver-threshold=5
fraud.repeat-transfer-threshold=5
fraud.high-amount-threshold=150000
fraud.high-amount-count-threshold=5