spring:
  application:
    name: finpulse

  profiles.active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  sql:
    init:
      mode: never


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

server:
  port: 8080

management:
  metrics:
    tags:
      application: finpulse
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true


fraud:
  amount-outlier:
    zscore-threshold: 4

  dormant-reactivation:
    dormancy-days: 60


brevo:
  api:
    key: ${BREVO_API_KEY:}
    base-url: https://api.brevo.com
  sender:
    email: ${BREVO_SENDER_EMAIL:test@finpulse.local}
    name: ${BREVO_SENDER_NAME:FinPulse}

jwt:
  secret: ${JWT_SECRET:this_is_a_dummy_secret_key_32chars_minimum}
  access-token-expiry-minutes: 30
  refresh-token-expiry-days: 3

app:
  frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
